
services:
  web:
    build: .
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    environment:
      - DATABASE_URL=postgresql://postgres:12345@db:5432/telemetry
      - SECRET_KEY=${SECRET_KEY:-your_default_secret_key}
      - PORT=${PORT:-5000}
      - FLASK_APP=${FLASK_APP:-app.py}
      - FLASK_ENV=${FLASK_ENV:-development}
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=telemetry
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: