"""Initial tables

Revision ID: 798733991e03
Revises: e85453c68fce
Create Date: 2025-10-15 17:53:33.231216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '798733991e03'
down_revision = 'e85453c68fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetry')
    # ### end Alembic commands ###
